server:
  port: 8888

spring:
  application:
    name: SPRING-CLOUD-CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/pksanthoshkumar/SpringCloud.git
          clone-on-start: true
          default-label: main  # Explicitly specify the branch if necessary

logging:
  file:
    name: logs/spring-cloud-config.log
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG  # Enable debug for detailed logging

