spring:
  application:
    name: EUREKA-CLIENT-ACCOUNTS
  graphql:
    graphiql:
      enabled: true
      path: /graphiql


logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
