eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 8761

spring:
  application:
    name: EUREKA-CLOUD-SERVER



logging:
  file:
    name: logs/spring-cloud-Eureka.log
  level:
    root: INFO
