server:
  port: 8083

spring:
  application:
    name: SPRING-CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EUREKA-CLIENT-ADDRESS
          uri: http://localhost:8081/
          predicates:
            - Path=/address/graphql  # Correct the predicate format
        - id: EUREKA-CLIENT-ACCOUNTS
          uri: http://localhost:8080/
          predicates:
            - Path=/accounts/graphql  # Correct the predicate format


logging:
  file:
    name: logs/spring-cloud-gateway.log
  level:
    root: INFO
